let yourName = prompt('What is your name?')
let favoriteMovie =prompt('What is your favorite movie')
let favoritefood = prompt('What is favorite food?')
 confirm(`${yournName} your favorite movie is ${favoritMovie} and you love ${favoritFood}`)
 //let all answers = yournName + ' ' + your favorite movei is' + '+favoriteMovie + ' ' + ' and you love' + ' ' +favoritefood
 console.log(`${yourName} your favorite movie is ${favoriteMovie} and you love ${favoriteFood}`)